### ISSUE TITLE
Padding appears on HTML Widget upon Preview if the width/height settings are in the Presentation's full resolution

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/widget-html#21]
**How it works now**
1. Create a new 1920x1080 presentation.  Assign a different background color to make the padding obvious.
2. Use the HTML Widget to embed a an iframe content with width=1920 and height=1080
3. Set the placeholder properties to 1920 and 1080
3. Save and publish.

In RVA and the new Editor, you will see that there is a margin/padding. <a href="https://apps.risevision.com/editor/workspace/0bcc4a63-b0a4-46b3-b559-edd00682a3d8/?cid=960b72df-9af7-476b-8a47-b67ded4c779d">See this presentation</a>

**How it should work**
When I embed a HTML Widget in a 1920x1080 Placeholder in a 1920x1080 Presentation, I expect that the Widget will occupy the entire presentation space.

One case of this via Community https://community.risevision.com/rise_vision_inc/topics/8px-margin-in-html-widget

**Comment by hcs0** [comment]
FYI @alanclayton

**Comment by donnapep** [comment]
@hcs0 @alanclayton This isn't a problem with the Widget. It's a problem with the content that is being put inside of the Widget. The `body` tag has a margin by default. In order to get rid of it, you need to add the following CSS inside the `<head>` tag:
    <style>
      body { margin: 0; }
    </style>`

**Comment by donnapep** [comment]
@hcs0 Can you confirm and close? Thx.

**Comment by hcs0** [comment]
@donnapep Verified and closed, also since it's related to the content within the Widget
