### ISSUE TITLE
When HTML Widget is in Playlist with other items, only top 1/3 shows up after 1st cycle.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-html#22]
**How to recreate**
1. Create a presentation with an HTML Widget and Video Widget in the same placeholder.
2. Add the following code into the HTML Widget 
<script src="//instansive.com/widget/js/instansive.js"></script><iframe src="//instansive.com/widgets/c2957aea001ae52d761631aaddd9b3b5f7c6a3cb.html" id="instansive_c2957aea00" name="instansive_c2957aea00"  scrolling="no" allowtransparency="true" class="instansive-widget" style="width: 100%; border: 0; overflow: hidden;"></iframe></iframe>
3. Save and preview the presentation

**What happens**
The second time through only the top 1/3 of the HTML page appears

**What should happen**
The HTML Widget should display the entire HTML page, regardless of if there are other items in the playlist.

**Presentation**
http://rva.risevision.com/#/PRESENTATION_MANAGE/id=216b15b4-0659-4b79-8a56-fb0c41ce4c41?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

**Notes**

- This happens on Preview, and in Rise Player, on all OSes.
- I have a workaround for the user that reported this issue, it involves removing some of the HTML code, specifically <script src="//instansive.com/widget/js/instansive.js"></script>.
- This issue is NOT present in the HTML Item. This exact HTML works perfectly in the HTML Item.

**Comment by alanclayton** [comment]
@btfrise Given you have a work around fix this when we start html epic. Thanks!

**Comment by alanclayton** [comment]
@btfrise Can you confirm add the height attribute (height=100%) and confirm if you still have the problem? Or just review this [Presentation](http://rva.risevision.com/#/PRESENTATION_MANAGE/id=8b023206-255d-43d1-96e6-5ee40bacef35?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55).

**Comment by alanclayton** [comment]
@btfrise never heard back on this. Can you review and let me know. Thanks

**Comment by btfrise** [comment]
@alanclayton I can't recreate this. It looks like the original embedded widget is now no longer working at all with either the HTML Widget or Item. I'm going to go ahead and close this.
