### ISSUE TITLE
HTML Widget causes cross domain issue.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-html#23]
**How to recreate**
1. Add an HTML Widget and HTML Item to the same presentation.
2. Add the following code to both presentations:
`<!DOCTYPE html>

<html>

<head>

<meta http-equiv='Content-Type' content='text/html;charset=UTF-8' />

<script type='text/javascript' src='http://208.118.102.5:3939/jsv/SncViewer.js'></script>

</head>

<body onload="new SNC.viewer('MyViewer', {sz:'5',ptz:'1',fps:'15',frm:'0',iPS:'1'})">

<div style='margin:30px' id='MyViewer'></div>

</body>

</html>`
3. Save and preview the presentation

**What happens**
The HTML Widget does not display content, the HTML Item does display content.

**What should happen**
Both placeholder should display content.

**Notes**
In console, the following errors are seen http://www.screencast.com/t/dCfQzEtb1

The only current workaround for this user is to continue using the HTML Item.

**Comment by btfrise** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/btf@risevision.com/conversations/2081893724

**Comment by alanclayton** [comment]
@btfrise Unable to replicate using [this Presentation.](http://goo.gl/CHkpVn) with Electron Player. Closing issue.
