### ISSUE TITLE
HTML Widget loading behaviour differs to HTML Item for images

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/widget-html#24]
**How to recreate**
Embed a series of HTML Widgets using the img tag
To compare, embed a series of HTML Items using the img tag.

You can use this [Presentation](https://rva.risevision.com/#/PRESENTATION_MANAGE/id=6037d9c7-f88e-4059-a3df-5ef3ca23e6d8?cid=960b72df-9af7-476b-8a47-b67ded4c779d) to compare.

You can use this [Schedule](https://rva.risevision.com/#/SCHEDULE_MANAGE/id=0d478438-ad7e-4b54-a609-c619dff5181d?cid=960b72df-9af7-476b-8a47-b67ded4c779d) to compare.

You can use Display ID 3CRT5D2VJG6P to check.

**What happens**
Different loading behaviours for <img> in the HTML Widget is observed when compared to the HTML Item.  The user can see the image loading from top to bottom.  This does not happen 100% of the time though but it is noticeable when it happens.

**What should happen**
The loading behaviour is not noticed by the user.  

**Notes**
Images are hosted on Google Drive 
Seen on installer version 2016.04.22.21.12 - Chrome 49

**Comment by hcs0** [comment]
https://community.risevision.com/rise_vision_inc/topics/html-reloading-each-time

**Comment by alanclayton** [comment]
Unable to replicate and no top-to-bottom rendering of images observed with Image Widget in this Presentation, http://rva.risevision.com/#/PRESENTATION_MANAGE/id=89165a8a-6433-4aad-9328-e7c14b800f26?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55
