### ISSUE TITLE
When embedding Google Slides, HTML Widget shows scroll bars.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-html#25]
**Issue description**
When a Google Slide embed code is added to an HTML Widget, it appears in preview and on display with scroll bars. When the same embed code is added to an HTML Item, is appears in preview and on display with **no** scroll bars.

**Presentations**
HTML Widget - https://goo.gl/CVf0yv
HTML Item - https://goo.gl/BQfhoQ

Windows 10 x64
RisePlayerElectron 2016.11.03.15.19
Chrome 52.0.2743.82
Chrome 54.0.2840.71 (64-bit)

**Comment by SMUchacz** [comment]
When I use the HTML widget it is also adding a scroll bar to each instance of the widget. Is the HTML widget being adding to the presentation as an iframe? If so, can it be modifier to add scrolling="no" in the iframe tag to remove the scroll bar?

**Comment by kerbyengen** [comment]
As I understand it you cannot use the scrolling="no" in the HTML widget because it is no longer supported. Does anyone have another solution for removing the scroll bars for embedded Google Slides?

**Comment by sheadarlison** [comment]
@btfrise I don't think this is a defect. The HTML Widget renders the HTML that is put in it, if you don't add HTML to hide the scroll bars they will show. I would suggest adding style="overflow: hidden;" do the body element in the HTML Widget and the scroll bars won't show on a display. Closing this issue. 

Thanks

![screen shot 2018-04-12 at 3 05 15 pm](https://user-images.githubusercontent.com/9273546/38698431-ffdb17aa-3e62-11e8-86df-8a1cf7f4a657.png)
